"""
Answer schemas for generated responses.

Represents answers and citations generated by the system.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional


@dataclass
class Citation:
    """
    A citation for a piece of information in an answer.
    
    Links a fact in the answer back to its source document.
    """

    document_name: str
    """Name of the source document."""

    chunk_id: str
    """Unique identifier of the source chunk."""

    page: Optional[int] = None
    """Page number in source document."""

    section: Optional[str] = None
    """Section title in source document."""

    subsection: Optional[str] = None
    """Subsection title if applicable."""

    title: Optional[str] = None
    """Title or heading of the relevant section."""

    relevance_score: float = 1.0
    """Reranker score indicating relevance (0.0-1.0)."""

    def to_string(self) -> str:
        """
        Get human-readable citation string.
        
        Returns:
            str: Formatted citation.
        """
        parts = [self.document_name]
        if self.page:
            parts.append(f"p. {self.page}")
        if self.section:
            parts.append(self.section)
        return " | ".join(parts)


@dataclass
class AnswerResponse:
    """
    Complete answer response from the RAG system.
    
    Includes the generated answer, citations, and metadata.
    """

    answer: str
    """The generated answer text."""

    citations: List[Citation]
    """List of source citations."""

    query: str
    """Original user query."""

    query_id: str
    """Unique identifier for the query."""

    answer_id: str = field(default_factory=str)
    """Unique identifier for this answer."""

    timestamp: datetime = field(default_factory=datetime.utcnow)
    """When answer was generated."""

    # Performance Metrics
    retrieval_latency_ms: float = 0.0
    """Time taken for retrieval in milliseconds."""

    generation_latency_ms: float = 0.0
    """Time taken for generation in milliseconds."""

    total_latency_ms: float = 0.0
    """Total end-to-end latency in milliseconds."""

    # Context Information
    context_chunks_count: int = 0
    """Number of chunks used in context."""

    context_tokens_count: int = 0
    """Total tokens in context."""

    # Quality Metrics
    confidence_score: float = 0.5
    """Confidence in answer quality (0.0-1.0)."""

    has_sufficient_context: bool = True
    """Whether sufficient context was available."""

    def get_citation_text(self) -> str:
        """
        Get formatted citation text for the answer.
        
        Returns:
            str: Formatted citations.
        """
        if not self.citations:
            return "No citations available"
        return "\n".join([f"[{i+1}] {c.to_string()}" for i, c in enumerate(self.citations)])

    def to_dict(self) -> dict:
        """
        Convert to dictionary for serialization.
        
        Returns:
            dict: Dictionary representation.
        """
        return {
            "answer": self.answer,
            "citations": [c.__dict__ for c in self.citations],
            "query": self.query,
            "query_id": self.query_id,
            "answer_id": self.answer_id,
            "timestamp": self.timestamp.isoformat(),
            "retrieval_latency_ms": self.retrieval_latency_ms,
            "generation_latency_ms": self.generation_latency_ms,
            "total_latency_ms": self.total_latency_ms,
            "context_chunks_count": self.context_chunks_count,
            "context_tokens_count": self.context_tokens_count,
            "confidence_score": self.confidence_score,
            "has_sufficient_context": self.has_sufficient_context,
        }
